# Generated by Django 6.0.6 on 2026-07-04 09:28

import app2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'In-Store Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending/Preparing'), ('dispatched', 'Dispatched / Out for Delivery'), ('delivered', 'Delivered / Collected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=app2.models.receipt_upload_path),
        ),
    ]
