# Generated by Django 6.0.6 on 2026-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_order_delivery_method_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending/Preparing'), ('dispatched', 'Dispatched / Out for Delivery'), ('delivered', 'Delivered'), ('ready_for_pickup', 'Ready for Collection'), ('picked_up', 'Picked Up / Collected')], default='pending', max_length=20),
        ),
    ]
