# Generated by Django 6.0.6 on 2026-07-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='os',
            field=models.CharField(blank=True, null=True),
        ),
    ]
