# Generated by Django 6.0.6 on 2026-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_laptop_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
